### ISSUE TITLE
Intents dont launch, only invocation name.

### ISSUE THREAD

**Issue by cnpants** [alexa/skill-sample-python-fact#8]
Hello! When sample utterance are used, it doesn't execute the functions. However using the invocation will.

**Comment by charany1** [comment]
same here , what might be causing this issue ?

**Comment by charany1** [comment]
For those coming from google search , check this out : https://forums.developer.amazon.com/questions/185916/alexa-simulator-not-responding-to-utterances.html


Basically since the sample skill doesn't sends should_end_session': False as Response which ends the session .

Add below code after this line : https://github.com/alexa/skill-sample-python-fact/blob/master/lambda/py/lambda_function.py#L76 

`handler_input.response_builder.set_should_end_session(False)`

and your session will be maintained and you would be able to ask facts using utterances only without using invocation name each time  and Alexa respone in lambda would appear something like below : 


`Alexa Response: {'can_fulfill_intent': None,
'card': {'content': 'The temperature inside the Sun can reach 15 million '
'degrees Celsius.',
'object_type': 'Simple',
'title': 'Space Facts'},
'directives': None,
'output_speech': {'object_type': 'SSML',
'ssml': "<speak>Here's your fact: The temperature inside "
'the Sun can reach 15 million degrees '
'Celsius.</speak>'},
'reprompt': None,
'should_end_session': False}`

**Comment by franklin-lobb** [comment]
I believe the issue may have been related to a bug in the canHandle condition that has been fixed. If the issue still persists, please reopen the issue.  For now closing.
